-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS electrodomesticos.proveedores
(
    id serial,
    nombre character varying(100) NOT NULL,
    direccion character varying(100) NOT NULL,
    correo_electronico character varying(100) NOT NULL,
    telefono character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS electrodomesticos.productos
(
    id serial,
    proveedor_id integer,
    nombre character varying(100) NOT NULL,
    precio numeric(13, 2) NOT NULL,
    cantidad integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS electrodomesticos.productos
    ADD FOREIGN KEY (proveedor_id)
    REFERENCES electrodomesticos.proveedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;